apiVersion: apps/v1
kind: Deployment
metadata:
  name: blood-donation-frontend
  namespace: 2401021
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blood-donation-frontend
  template:
    metadata:
      labels:
        app: blood-donation-frontend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: frontend
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/blood-app/blood-donation-app-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blood-donation-frontend-service
  namespace: 2401021
spec:
  selector:
    app: blood-donation-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
