apiVersion: v1
kind: Service
metadata:
  name: blood-donation-frontend
  labels:
    app: blood-donation-frontend
spec:
  selector:
    app: blood-donation-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer