apiVersion: apps/v1
kind: Deployment
metadata:
  name: blood-donation-frontend
  labels:
    app: blood-donation-frontend
    project: "2401021"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blood-donation-frontend
  template:
    metadata:
      labels:
        app: blood-donation-frontend
    spec:
      containers:
      - name: frontend
        image: blood-donation-frontend:latest  # This gets replaced by Jenkins
        ports:
        - containerPort: 3000  # Frontend port
        env:
        - name: REACT_APP_API_URL
          value: "http://blood-donation-backend:5000"