apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blood-donation-ingress
  namespace: 2401021
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: blood.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blood-donation-frontend-service
                port:
                  number: 80
